// Kekich's 100 Credos
const KEKICH_CREDOS = [
    { id: 1, text: "People will do almost anything to stay in their comfort zones. If you want to accomplish anything, get out of your comfort zone. Strive to increase order and discipline in your life. Discipline usually means doing the opposite of what you feel like doing.", category: "discipline" },
    { id: 2, text: "Cherish time, your most valuable resource. You can never make up the time you lose. It's the most important value for any productive happy individual and is the only limitation to all accomplishment.", category: "time" },
    { id: 3, text: "Think carefully before making any offers, commitments or promises, no matter how seemingly trivial. These are all contracts and must be honored.", category: "integrity" },
    { id: 4, text: "Real regrets only come from not doing your best. All else is out of your control. You're measured by results only. Trade excuses and 'trying' for results.", category: "results" },
    { id: 5, text: "Always show gratitude when earned, monetarily when possible.", category: "relationships" },
    { id: 6, text: "Produce for wealth creation and accumulation. Invest profits for wealth preservation and growth. Produce more than you consume and save a minimum of 20% of all earnings. Pay yourself first.", category: "wealth" },
    { id: 7, text: "You're successful when you like who and what you are. Success includes achievement while choosing and directing your own activities.", category: "success" },
    { id: 8, text: "Learn from the giants.", category: "learning" },
    { id: 9, text: "A little caution avoids great regrets. Hope for the best and prepare for the worst. Keep fully insured physically and materially.", category: "risk" },
    { id: 10, text: "Learn the other side's needs, offer as little information as possible, never underestimate your opposition, and never show weakness when negotiating.", category: "negotiation" },
    { id: 11, text: "Never enter into nor invest in a business without a solid, well-researched and well thought-out written plan. Execute the plan with passion and precision.", category: "planning" },
    { id: 12, text: "Success comes quickly to those whom develop great powers of intense sustained concentration. The first rule is to get involved by asking focused questions.", category: "focus" },
    { id: 13, text: "Protect your downside. The upside will take care of itself. Cut your losses short - and let your profits run.", category: "risk" },
    { id: 14, text: "The primary purpose of business is to create and keep customers. Marketing and innovation produce results. All other business functions are costs.", category: "business" },
    { id: 15, text: "If it's not proprietary, it won't work. Pay only on performance. Proprietary interest is one of the most powerful forces ever known.", category: "business" },
    { id: 16, text: "Competence starts with guaranteeing your work.", category: "integrity" },
    { id: 17, text: "Life operates in reverse action to entropy. Therefore the universe is hostile to life. Progress is a continued effort to swim against the stream.", category: "philosophy" },
    { id: 18, text: "Find out what works, and then do more of it. Focus first on doing the right things, and then on doing things right by mastering details.", category: "effectiveness" },
    { id: 19, text: "Use leverage with ideas, work, money, time and people. To maximize profits, replicate yourself. Earning potentials become geometric rather than linear.", category: "leverage" },
    { id: 20, text: "Rationalizations are generally convenient evasions of reality and are used as excuses for dishonest behavior, mistakes and/or laziness.", category: "honesty" },
    { id: 21, text: "Always have lofty explicit goals and visualize them intensely. Assume the attitude that if you don't reach your goals, you will literally die!", category: "goals" },
    { id: 22, text: "The value of any service you have to offer diminishes rapidly once it's provided. Protect your compensation before performing.", category: "business" },
    { id: 23, text: "Every day should be a celebration of existence. You are a masterpiece of life and should feel and appreciate this all the way down to your bones.", category: "gratitude" },
    { id: 24, text: "Enthusiasm covers many deficiencies - and will make others want to associate with you.", category: "attitude" },
    { id: 25, text: "Working for someone else gives you little chance to make a fortune. By owning your own business, you only have to be good to become wealthy.", category: "entrepreneurship" },
    { id: 26, text: "Religiously nourish your body with proper nutrition, exercise, recreation, sleep and relaxation techniques.", category: "health" },
    { id: 27, text: "The choice to exert integrated effort or to default to camouflaged laziness is the key choice that determines your character, competence and future.", category: "discipline" },
    { id: 28, text: "Keep an active mind, and continue to grow intellectually. You either grow or regress. Nothing stands still.", category: "learning" },
    { id: 29, text: "Most accomplishment (and problem avoidance) is built on clear persuasive communication. Become a communications expert.", category: "communication" },
    { id: 30, text: "Power comes from stripping away appearances and seeing things as they really are. Take full control of, and responsibility for, your conscious mind and every aspect of your life.", category: "power" },
    { id: 31, text: "If there is not a conscious struggle to be honest in difficult situations, you are probably being dishonest.", category: "honesty" },
    { id: 32, text: "Do not compromise if you are right. Hold your ground, show no fear, ask for what you want, and the opposition will usually agree.", category: "assertiveness" },
    { id: 33, text: "If the situation is not right in the long term, walk away from it. Maintain a long term outlook in all endeavors.", category: "perspective" },
    { id: 34, text: "Invest only after strict and complete due diligence. Don't allow yourself to be rushed. Make important decisions carefully, consider your gut feelings... then pull the trigger.", category: "decisions" },
    { id: 35, text: "Stress kills. No matter how painful in the short-term, remove all chronically stressful situations, environments and people from your life.", category: "health" },
    { id: 36, text: "Keep your overhead to a minimum. Rely more on brains, wit and talent... and less on money.", category: "resourcefulness" },
    { id: 37, text: "Business is the highest evolution of consciousness and morality. The essences of business are: honesty, effort, responsibility, integration, creativity, objectivity, long-range planning, intensity, effectiveness, discipline, thought and control.", category: "business" },
    { id: 38, text: "That which is most satisfying is that which is earned. Anything received free of charge is seldom valued.", category: "value" },
    { id: 39, text: "By adhering to a strong honest philosophy, you will remain guiltless, blameless, independent and maintain control over your life.", category: "philosophy" },
    { id: 40, text: "No dream is too big. It takes almost the same amount of time and energy to manage tiny projects or businesses as it does to manage massive ones.", category: "ambition" },
    { id: 41, text: "There is no such thing as 'just a little theft' or 'just a little dishonesty'.", category: "integrity" },
    { id: 42, text: "Lead by example.", category: "leadership" },
    { id: 43, text: "Take full responsibility for your actions or lack of action. He who errs must pay.", category: "responsibility" },
    { id: 44, text: "An hour of effective, precise, hard, disciplined - and integrated thinking can be worth a month of hard work. Thinking is the very essence of, and the most difficult thing to do in business and in life.", category: "thinking" },
    { id: 45, text: "Out-think, out-innovate and out-hustle the competition, and vividly visualize yourself as winning before entering into every deal or competitive situation.", category: "competition" },
    { id: 46, text: "First impressions are lasting impressions. Put your best foot forward. People treat you like you teach them to treat you.", category: "impression" },
    { id: 47, text: "The right thing is usually not the easy thing to do. You may sacrifice popularity for rightness, but you'll lose self-esteem for wrongness.", category: "integrity" },
    { id: 48, text: "If someone lies to you once, he'll lie to you a thousand times. Lying is for thieves and cowards.", category: "honesty" },
    { id: 49, text: "Have strict and total respect for other people's property.", category: "integrity" },
    { id: 50, text: "Producing results is more important than proving you're right. To get things done, try to understand others' frames of references, points of view, needs and wants.", category: "results" },
    { id: 51, text: "Long term success is built on credibility and on establishing enduring loving relationships with quality people based on mutually earned trust.", category: "relationships" },
    { id: 52, text: "Don't be preoccupied with things over which you have no control, and don't take things personally.", category: "mindset" },
    { id: 53, text: "Spend more time working 'on' your business than 'in' your business.", category: "business" },
    { id: 54, text: "Don't enter into a business relationship with anyone unknown to you without being furnished with references dating back at least 10 years.", category: "due-diligence" },
    { id: 55, text: "Enjoy life. Treat it as an adventure. Care passionately about the outcome, but keep it in perspective. Lighten up. You'll live longer.", category: "perspective" },
    { id: 56, text: "Identify exactly what it is you want. This takes a lot of thought. Then don't let anything stand in your way of getting it.", category: "goals" },
    { id: 57, text: "You can get any job done through the sheer force of will when combined with uncompromising integrity and competence. Strong leadership is the key.", category: "leadership" },
    { id: 58, text: "You are responsible for exactly who, what and where you are in life. That will be just as true this time next year. Situations aren't important. How you react to them is.", category: "responsibility" },
    { id: 59, text: "The foundation of achievement is intense desire. The world's highest achievers have the highest levels of dissatisfaction.", category: "motivation" },
    { id: 60, text: "Integrate every aspect of your life (body, mind, spirit, relationships, business) and each within itself.", category: "integration" },
    { id: 61, text: "Never be deceptive when trying to achieve a personal gain. Shortchanging others results in loss of self-esteem.", category: "integrity" },
    { id: 62, text: "If your purpose of life is security, you will be a failure. Security is the lowest form of happiness.", category: "ambition" },
    { id: 63, text: "Never enter into a contract unless all parties benefit. But no partnership is ever 50/50. There will always be inequities.", category: "partnerships" },
    { id: 64, text: "Review the basics of your profession at least once per year.", category: "mastery" },
    { id: 65, text: "Bitterness, jealousy and anger empower your enemies and enslave you. Forgive, learn your lessons, and get on with your life.", category: "mindset" },
    { id: 66, text: "Most people spend 90% of their time on what they're not best at. Geniuses delegate the 90%... and spend all their time on their 'unique ability'.", category: "leverage" },
    { id: 67, text: "High self-esteem can only come from moral productivity and achievement.", category: "self-esteem" },
    { id: 68, text: "There are an infinite number of new opportunities. Actively seek them out, and position yourself to recognize and take advantage of them.", category: "opportunity" },
    { id: 69, text: "There is no such thing as a good idea unless it is developed and utilized.", category: "execution" },
    { id: 70, text: "For maximum profits, identify and market universal needs, wants and trends.", category: "business" },
    { id: 71, text: "To maximize opportunities, seek and master the complicated. The major solutions you find will be surprisingly simple.", category: "opportunity" },
    { id: 72, text: "Always have options. Options are a primary source of power.", category: "power" },
    { id: 73, text: "Nothing wins more often than superior preparation. Genius is usually preparation.", category: "preparation" },
    { id: 74, text: "Patience is profitable. Achievement comes from the sum of consistent small efforts, repeated daily.", category: "persistence" },
    { id: 75, text: "Persistence is a sure path to success with quality activities. Never, ever, ever give up.", category: "persistence" },
    { id: 76, text: "'I will do this' is the only attitude that works. 'I'll try' or 'I think' doesn't work.", category: "commitment" },
    { id: 77, text: "Always work on increasing the size of the pie, rather than just your portion.", category: "abundance" },
    { id: 78, text: "Rewards are rare without risks, but take only carefully calculated risks. Make sure the odds are on your side.", category: "risk" },
    { id: 79, text: "The 'how' you get it (with integrity) is more important than the 'what'.", category: "integrity" },
    { id: 80, text: "Be explicit and semantically precise in all communications, agreements and dealings. Putting agreements in writing avoids misunderstandings.", category: "communication" },
    { id: 81, text: "The best way to get started is to get started. Life rewards action... not reaction. Wait for nothing. Attack life.", category: "action" },
    { id: 82, text: "Question everything. Don't believe it's true or right just because it's conventional. Be flexible, and be willing to turn on a dime when advantageous.", category: "thinking" },
    { id: 83, text: "Have fun. The single key to a successful happy life is finding a vocation you enjoy - one that excites you the most.", category: "fulfillment" },
    { id: 84, text: "Nobody gets old by surprise.", category: "awareness" },
    { id: 85, text: "When it's a matter of producing or starving, people don't starve.", category: "survival" },
    { id: 86, text: "You get what you expect, not what you want. Fill your life with positive expectations. Demand the best.", category: "expectations" },
    { id: 87, text: "The surest way to accomplish your business goals is making service to others your primary goal. The key to success is adding value to others' lives.", category: "service" },
    { id: 88, text: "The source of lasting happiness can never come from outside yourself through consuming values - but only from within yourself by creating values.", category: "creation" },
    { id: 89, text: "Unattended problems will not go away, but will usually get worse. Anticipate and avoid problems - or meet them head on at the outset.", category: "problems" },
    { id: 90, text: "Find an excuse to laugh every chance you get, especially when you least feel like it.", category: "humor" },
    { id: 91, text: "When someone makes a big issue about his honesty or achievements, he is probably dishonest or a failure.", category: "discernment" },
    { id: 92, text: "Put the magic power of compound interest to work with every available dollar.", category: "wealth" },
    { id: 93, text: "The best investment you will ever make is your steady increase of knowledge. Invest in yourself. Thirty minutes of study per day eventually makes you an expert.", category: "learning" },
    { id: 94, text: "For each important action you take, ask yourself if you would be embarrassed if it were published. It takes a lifetime of effort to build a good reputation but only a moment of stupidity to destroy it.", category: "reputation" },
    { id: 95, text: "You are exactly what you believe and think about all day long. Constantly monitor your thoughts.", category: "mindset" },
    { id: 96, text: "Skepticism is a key to rational thinking. Be especially skeptical of your own cherished beliefs.", category: "thinking" },
    { id: 97, text: "Anxiety is usually caused by lack of control, organization, preparation and action.", category: "anxiety" },
    { id: 98, text: "The first rule of sharpening your mind is to be an alert and sensitive observer. Assume nothing. Refuse to be swayed by emotion when it conflicts with reason.", category: "observation" },
    { id: 99, text: "Experience is not what happens to you. It's what you do with what happens to you. It takes a wise man to learn from his own mistakes... and a genius to learn and profit from the mistakes of others.", category: "experience" },
    { id: 100, text: "The purpose of life is to delay, avoid and eventually reverse death.", category: "purpose" }
];

// Paul's TRDC Paulisms
const PAULISMS = [
    { id: 1, title: "No Surprises", truth: "You can't lead from the front if you're always reacting from behind.", code: ["Don't chase perfect. Chase early awareness.", "Give your team the language: 'This may be nothing, but I want to get it on your radar...'", "Silence isn't safety - it's risk disguised as calm."], category: "leadership" },
    { id: 2, title: "Think Win/Win", truth: "If the solution only serves you, it's not a solution. It's a power move.", code: ["In any deadlock, ask: 'What outcome preserves power and reputation on both sides?'", "Win-win doesn't mean 50/50 - it means everyone walks away stronger.", "Pick up the damn phone. Most 'unresolvable' battles exist because no one's brave enough to lead the room."], category: "negotiation" },
    { id: 3, title: "Mistakes = Learning", truth: "Mistakes aren't the enemy. Denial is.", code: ["The mistake wasn't hiring the wrong person - it was ignoring your gut when it was screaming at you.", "Speed without awareness is arrogance disguised as urgency.", "When it's your fault, say it out loud. Teams don't follow perfection. They follow responsibility."], category: "growth" },
    { id: 4, title: "Be Proactive", truth: "Being proactive isn't about staying ahead of a fire. It's about anticipating what your client needs before they even know it themselves.", code: ["Proactive isn't about motion - it's about anticipation.", "Strategy is rapport. When you solve before you're asked, you earn trust before you need it.", "Customize your approach. SOPs don't win over unique personalities. Strategic empathy does."], category: "strategy" },
    { id: 5, title: "Feedback is Immediate", truth: "What you tolerate in silence, you endorse in culture.", code: ["Feedback delayed is culture compromised.", "Make 'course correction' a normal part of your day-to-day.", "Micromanagement isn't watching too closely - it's leading too late."], category: "leadership" },
    { id: 6, title: "Say YES When It's YES, NO When It's NO", truth: "Indecision costs more than the wrong decision - because it leaves the problem bleeding out while everyone watches.", code: ["If your gut and the facts are aligned - decide, declare, and document.", "Win-win doesn't mean weak. You don't owe a yes just because someone's asking nicely.", "Say YES when it's YES. Say NO when it's NO. Everything else creates chaos."], category: "decisions" },
    { id: 7, title: "Own Your Growth", truth: "If you're waiting for someone to tap you on the shoulder and promote you, you've already plateaued.", code: ["No one's coming to rescue your potential.", "A+ performers ask what they need to do. B-level performers wait to be noticed.", "Growth isn't optional. Comfort is the real career ceiling."], category: "growth" },
    { id: 8, title: "Guidance > Micromanagement", truth: "If you're still doing all the work, you're not leading - you're blocking the people who could.", code: ["If you're involved in every task, you're training your team to underperform.", "Micromanagement is a symptom of mistrust. Fix the culture, not the control.", "Your job isn't to touch every play - it's to design the playbook and coach the team that runs it."], category: "leadership" },
    { id: 9, title: "Fight for the Best Idea, Not Your Ego", truth: "If you're the smartest person in the room, but no one can challenge you, you're actually the most dangerous.", code: ["If someone on your team has a better angle - back off and back them up.", "Ego is expensive. Empowerment is scalable.", "The best idea wins - even if it's not mine."], category: "humility" },
    { id: 10, title: "Use Your Gut (When Earned)", truth: "Your gut is only as good as your reps. If you haven't earned it, don't trust it.", code: ["Gut instincts come from exposure. The more you've solved, the more reliable your signals become.", "Document your gut wins.", "Reps build rhythm. Rhythm builds instinct."], category: "intuition" },
    { id: 11, title: "Under-Promise, Over-Deliver", truth: "Trust isn't built in grand gestures - it's stacked in small moments of overdelivery.", code: ["Know the true expectation. Deliver that - then exceed it.", "Don't fake timelines. Add space. Then beat the clock.", "Make over-delivery a daily rhythm, not a marketing stunt."], category: "trust" }
];
